region: Asia

blacklisted-blocks:
  - LAVA
  - WATER
  - CACTUS
  - MAGMA_BLOCK
  - SEAPICKLE
  - KELP
  - SEAGRASS
  - LILY_PAD
  - FIRE
  - CAMPFIRE
  - SOUL_CAMPFIRE
  - WITHER_ROSE
  - VOID_AIR
  - CAVE_AIR
  - AIR

# GTA V Style Camera Teleportation Effect
camera-effect:
  enabled: true
  ascend-height: 80.0
  ascend-duration-ticks: 30
  pan-duration-ticks: 35
  descend-duration-ticks: 30
  preload-chunk-radius: 2
  sound-effects: true