pending-timeout: 60
request-cooldown: 10


# Worlds that cannot be selected or used as duel arenas (e.g. main survival worlds)
# This prevents accidentally resizing the WorldBorder of survival, spawn, nether, end, etc.
blacklisted-worlds:
  - "world"
  - "world_nether"
  - "world_the_end"
  - "spawn"