chat-filter:
  cooldown-ms: 2000
  block-repeats: true
  max-length: 256
  bad-words:
    - "hitler"
    - "nazi"
    - "nazi germany"
    - "nigger"
    - "nigga"
    - "niga"
    - "niger"
    - "fuck"
    - "bitch"
    - "asshole"
    - "ass"
    - "gay"
    - "fuckyou"
    - "shutthefuckup"
    - "stfu"
    - "dick"
    - "pussy"
    - "dckhead"
    - "bitches"
    - "fucking"
    - "cock"
    - "vagina"
    - "cum"
    - "cumming"
    - "blowjob"
    - "suckmycock"
    - "suckmydick"
    - "motherfucker"
    - "idgaf"
    - "idontgiveafuck"
    - "sex"